/**
 * This code was generated by Builder.io.
 */
import React from "react";

import MainContent from "./MainContent";

import styles from "./Apps.module.css";

const Apps = () => {
  return (
    <div className={styles.app}>
      
      <MainContent />
      
    </div>
  );
};

export default Apps;